# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hugo/Git/libopenTIDAL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hugo/Git/libopenTIDAL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hugo/Git/libopenTIDAL/CMakeFiles /Users/hugo/Git/libopenTIDAL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hugo/Git/libopenTIDAL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openTIDAL

# Build rule for target.
openTIDAL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openTIDAL
.PHONY : openTIDAL

# fast build rule for target.
openTIDAL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/build
.PHONY : openTIDAL/fast

Source/OTAlloc.o: Source/OTAlloc.c.o

.PHONY : Source/OTAlloc.o

# target to build an object file
Source/OTAlloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTAlloc.c.o
.PHONY : Source/OTAlloc.c.o

Source/OTAlloc.i: Source/OTAlloc.c.i

.PHONY : Source/OTAlloc.i

# target to preprocess a source file
Source/OTAlloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTAlloc.c.i
.PHONY : Source/OTAlloc.c.i

Source/OTAlloc.s: Source/OTAlloc.c.s

.PHONY : Source/OTAlloc.s

# target to generate assembly for a file
Source/OTAlloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTAlloc.c.s
.PHONY : Source/OTAlloc.c.s

Source/OTBase64.o: Source/OTBase64.c.o

.PHONY : Source/OTBase64.o

# target to build an object file
Source/OTBase64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTBase64.c.o
.PHONY : Source/OTBase64.c.o

Source/OTBase64.i: Source/OTBase64.c.i

.PHONY : Source/OTBase64.i

# target to preprocess a source file
Source/OTBase64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTBase64.c.i
.PHONY : Source/OTBase64.c.i

Source/OTBase64.s: Source/OTBase64.c.s

.PHONY : Source/OTBase64.s

# target to generate assembly for a file
Source/OTBase64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTBase64.c.s
.PHONY : Source/OTBase64.c.s

Source/OTDealloc.o: Source/OTDealloc.c.o

.PHONY : Source/OTDealloc.o

# target to build an object file
Source/OTDealloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTDealloc.c.o
.PHONY : Source/OTDealloc.c.o

Source/OTDealloc.i: Source/OTDealloc.c.i

.PHONY : Source/OTDealloc.i

# target to preprocess a source file
Source/OTDealloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTDealloc.c.i
.PHONY : Source/OTDealloc.c.i

Source/OTDealloc.s: Source/OTDealloc.c.s

.PHONY : Source/OTDealloc.s

# target to generate assembly for a file
Source/OTDealloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTDealloc.c.s
.PHONY : Source/OTDealloc.c.s

Source/OTHttp.o: Source/OTHttp.c.o

.PHONY : Source/OTHttp.o

# target to build an object file
Source/OTHttp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTHttp.c.o
.PHONY : Source/OTHttp.c.o

Source/OTHttp.i: Source/OTHttp.c.i

.PHONY : Source/OTHttp.i

# target to preprocess a source file
Source/OTHttp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTHttp.c.i
.PHONY : Source/OTHttp.c.i

Source/OTHttp.s: Source/OTHttp.c.s

.PHONY : Source/OTHttp.s

# target to generate assembly for a file
Source/OTHttp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTHttp.c.s
.PHONY : Source/OTHttp.c.s

Source/OTHttpParse.o: Source/OTHttpParse.c.o

.PHONY : Source/OTHttpParse.o

# target to build an object file
Source/OTHttpParse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTHttpParse.c.o
.PHONY : Source/OTHttpParse.c.o

Source/OTHttpParse.i: Source/OTHttpParse.c.i

.PHONY : Source/OTHttpParse.i

# target to preprocess a source file
Source/OTHttpParse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTHttpParse.c.i
.PHONY : Source/OTHttpParse.c.i

Source/OTHttpParse.s: Source/OTHttpParse.c.s

.PHONY : Source/OTHttpParse.s

# target to generate assembly for a file
Source/OTHttpParse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTHttpParse.c.s
.PHONY : Source/OTHttpParse.c.s

Source/OTJson.o: Source/OTJson.c.o

.PHONY : Source/OTJson.o

# target to build an object file
Source/OTJson.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTJson.c.o
.PHONY : Source/OTJson.c.o

Source/OTJson.i: Source/OTJson.c.i

.PHONY : Source/OTJson.i

# target to preprocess a source file
Source/OTJson.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTJson.c.i
.PHONY : Source/OTJson.c.i

Source/OTJson.s: Source/OTJson.c.s

.PHONY : Source/OTJson.s

# target to generate assembly for a file
Source/OTJson.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTJson.c.s
.PHONY : Source/OTJson.c.s

Source/OTPersistent.o: Source/OTPersistent.c.o

.PHONY : Source/OTPersistent.o

# target to build an object file
Source/OTPersistent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTPersistent.c.o
.PHONY : Source/OTPersistent.c.o

Source/OTPersistent.i: Source/OTPersistent.c.i

.PHONY : Source/OTPersistent.i

# target to preprocess a source file
Source/OTPersistent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTPersistent.c.i
.PHONY : Source/OTPersistent.c.i

Source/OTPersistent.s: Source/OTPersistent.c.s

.PHONY : Source/OTPersistent.s

# target to generate assembly for a file
Source/OTPersistent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTPersistent.c.s
.PHONY : Source/OTPersistent.c.s

Source/OTService/OTService.o: Source/OTService/OTService.c.o

.PHONY : Source/OTService/OTService.o

# target to build an object file
Source/OTService/OTService.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTService.c.o
.PHONY : Source/OTService/OTService.c.o

Source/OTService/OTService.i: Source/OTService/OTService.c.i

.PHONY : Source/OTService/OTService.i

# target to preprocess a source file
Source/OTService/OTService.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTService.c.i
.PHONY : Source/OTService/OTService.c.i

Source/OTService/OTService.s: Source/OTService/OTService.c.s

.PHONY : Source/OTService/OTService.s

# target to generate assembly for a file
Source/OTService/OTService.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTService.c.s
.PHONY : Source/OTService/OTService.c.s

Source/OTService/OTServiceAuth.o: Source/OTService/OTServiceAuth.c.o

.PHONY : Source/OTService/OTServiceAuth.o

# target to build an object file
Source/OTService/OTServiceAuth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceAuth.c.o
.PHONY : Source/OTService/OTServiceAuth.c.o

Source/OTService/OTServiceAuth.i: Source/OTService/OTServiceAuth.c.i

.PHONY : Source/OTService/OTServiceAuth.i

# target to preprocess a source file
Source/OTService/OTServiceAuth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceAuth.c.i
.PHONY : Source/OTService/OTServiceAuth.c.i

Source/OTService/OTServiceAuth.s: Source/OTService/OTServiceAuth.c.s

.PHONY : Source/OTService/OTServiceAuth.s

# target to generate assembly for a file
Source/OTService/OTServiceAuth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceAuth.c.s
.PHONY : Source/OTService/OTServiceAuth.c.s

Source/OTService/OTServiceFavorites.o: Source/OTService/OTServiceFavorites.c.o

.PHONY : Source/OTService/OTServiceFavorites.o

# target to build an object file
Source/OTService/OTServiceFavorites.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceFavorites.c.o
.PHONY : Source/OTService/OTServiceFavorites.c.o

Source/OTService/OTServiceFavorites.i: Source/OTService/OTServiceFavorites.c.i

.PHONY : Source/OTService/OTServiceFavorites.i

# target to preprocess a source file
Source/OTService/OTServiceFavorites.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceFavorites.c.i
.PHONY : Source/OTService/OTServiceFavorites.c.i

Source/OTService/OTServiceFavorites.s: Source/OTService/OTServiceFavorites.c.s

.PHONY : Source/OTService/OTServiceFavorites.s

# target to generate assembly for a file
Source/OTService/OTServiceFavorites.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceFavorites.c.s
.PHONY : Source/OTService/OTServiceFavorites.c.s

Source/OTService/OTServiceFeed.o: Source/OTService/OTServiceFeed.c.o

.PHONY : Source/OTService/OTServiceFeed.o

# target to build an object file
Source/OTService/OTServiceFeed.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceFeed.c.o
.PHONY : Source/OTService/OTServiceFeed.c.o

Source/OTService/OTServiceFeed.i: Source/OTService/OTServiceFeed.c.i

.PHONY : Source/OTService/OTServiceFeed.i

# target to preprocess a source file
Source/OTService/OTServiceFeed.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceFeed.c.i
.PHONY : Source/OTService/OTServiceFeed.c.i

Source/OTService/OTServiceFeed.s: Source/OTService/OTServiceFeed.c.s

.PHONY : Source/OTService/OTServiceFeed.s

# target to generate assembly for a file
Source/OTService/OTServiceFeed.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceFeed.c.s
.PHONY : Source/OTService/OTServiceFeed.c.s

Source/OTService/OTServicePlaylist.o: Source/OTService/OTServicePlaylist.c.o

.PHONY : Source/OTService/OTServicePlaylist.o

# target to build an object file
Source/OTService/OTServicePlaylist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServicePlaylist.c.o
.PHONY : Source/OTService/OTServicePlaylist.c.o

Source/OTService/OTServicePlaylist.i: Source/OTService/OTServicePlaylist.c.i

.PHONY : Source/OTService/OTServicePlaylist.i

# target to preprocess a source file
Source/OTService/OTServicePlaylist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServicePlaylist.c.i
.PHONY : Source/OTService/OTServicePlaylist.c.i

Source/OTService/OTServicePlaylist.s: Source/OTService/OTServicePlaylist.c.s

.PHONY : Source/OTService/OTServicePlaylist.s

# target to generate assembly for a file
Source/OTService/OTServicePlaylist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServicePlaylist.c.s
.PHONY : Source/OTService/OTServicePlaylist.c.s

Source/OTService/OTServiceStd.o: Source/OTService/OTServiceStd.c.o

.PHONY : Source/OTService/OTServiceStd.o

# target to build an object file
Source/OTService/OTServiceStd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceStd.c.o
.PHONY : Source/OTService/OTServiceStd.c.o

Source/OTService/OTServiceStd.i: Source/OTService/OTServiceStd.c.i

.PHONY : Source/OTService/OTServiceStd.i

# target to preprocess a source file
Source/OTService/OTServiceStd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceStd.c.i
.PHONY : Source/OTService/OTServiceStd.c.i

Source/OTService/OTServiceStd.s: Source/OTService/OTServiceStd.c.s

.PHONY : Source/OTService/OTServiceStd.s

# target to generate assembly for a file
Source/OTService/OTServiceStd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTService/OTServiceStd.c.s
.PHONY : Source/OTService/OTServiceStd.c.s

Source/OTSession.o: Source/OTSession.c.o

.PHONY : Source/OTSession.o

# target to build an object file
Source/OTSession.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTSession.c.o
.PHONY : Source/OTSession.c.o

Source/OTSession.i: Source/OTSession.c.i

.PHONY : Source/OTSession.i

# target to preprocess a source file
Source/OTSession.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTSession.c.i
.PHONY : Source/OTSession.c.i

Source/OTSession.s: Source/OTSession.c.s

.PHONY : Source/OTSession.s

# target to generate assembly for a file
Source/OTSession.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTSession.c.s
.PHONY : Source/OTSession.c.s

Source/OTSessionRefresh.o: Source/OTSessionRefresh.c.o

.PHONY : Source/OTSessionRefresh.o

# target to build an object file
Source/OTSessionRefresh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTSessionRefresh.c.o
.PHONY : Source/OTSessionRefresh.c.o

Source/OTSessionRefresh.i: Source/OTSessionRefresh.c.i

.PHONY : Source/OTSessionRefresh.i

# target to preprocess a source file
Source/OTSessionRefresh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTSessionRefresh.c.i
.PHONY : Source/OTSessionRefresh.c.i

Source/OTSessionRefresh.s: Source/OTSessionRefresh.c.s

.PHONY : Source/OTSessionRefresh.s

# target to generate assembly for a file
Source/OTSessionRefresh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTSessionRefresh.c.s
.PHONY : Source/OTSessionRefresh.c.s

Source/OTString.o: Source/OTString.c.o

.PHONY : Source/OTString.o

# target to build an object file
Source/OTString.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTString.c.o
.PHONY : Source/OTString.c.o

Source/OTString.i: Source/OTString.c.i

.PHONY : Source/OTString.i

# target to preprocess a source file
Source/OTString.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTString.c.i
.PHONY : Source/OTString.c.i

Source/OTString.s: Source/OTString.c.s

.PHONY : Source/OTString.s

# target to generate assembly for a file
Source/OTString.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTString.c.s
.PHONY : Source/OTString.c.s

Source/OTUrlEncode.o: Source/OTUrlEncode.c.o

.PHONY : Source/OTUrlEncode.o

# target to build an object file
Source/OTUrlEncode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTUrlEncode.c.o
.PHONY : Source/OTUrlEncode.c.o

Source/OTUrlEncode.i: Source/OTUrlEncode.c.i

.PHONY : Source/OTUrlEncode.i

# target to preprocess a source file
Source/OTUrlEncode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTUrlEncode.c.i
.PHONY : Source/OTUrlEncode.c.i

Source/OTUrlEncode.s: Source/OTUrlEncode.c.s

.PHONY : Source/OTUrlEncode.s

# target to generate assembly for a file
Source/OTUrlEncode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openTIDAL.dir/build.make CMakeFiles/openTIDAL.dir/Source/OTUrlEncode.c.s
.PHONY : Source/OTUrlEncode.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... openTIDAL"
	@echo "... Source/OTAlloc.o"
	@echo "... Source/OTAlloc.i"
	@echo "... Source/OTAlloc.s"
	@echo "... Source/OTBase64.o"
	@echo "... Source/OTBase64.i"
	@echo "... Source/OTBase64.s"
	@echo "... Source/OTDealloc.o"
	@echo "... Source/OTDealloc.i"
	@echo "... Source/OTDealloc.s"
	@echo "... Source/OTHttp.o"
	@echo "... Source/OTHttp.i"
	@echo "... Source/OTHttp.s"
	@echo "... Source/OTHttpParse.o"
	@echo "... Source/OTHttpParse.i"
	@echo "... Source/OTHttpParse.s"
	@echo "... Source/OTJson.o"
	@echo "... Source/OTJson.i"
	@echo "... Source/OTJson.s"
	@echo "... Source/OTPersistent.o"
	@echo "... Source/OTPersistent.i"
	@echo "... Source/OTPersistent.s"
	@echo "... Source/OTService/OTService.o"
	@echo "... Source/OTService/OTService.i"
	@echo "... Source/OTService/OTService.s"
	@echo "... Source/OTService/OTServiceAuth.o"
	@echo "... Source/OTService/OTServiceAuth.i"
	@echo "... Source/OTService/OTServiceAuth.s"
	@echo "... Source/OTService/OTServiceFavorites.o"
	@echo "... Source/OTService/OTServiceFavorites.i"
	@echo "... Source/OTService/OTServiceFavorites.s"
	@echo "... Source/OTService/OTServiceFeed.o"
	@echo "... Source/OTService/OTServiceFeed.i"
	@echo "... Source/OTService/OTServiceFeed.s"
	@echo "... Source/OTService/OTServicePlaylist.o"
	@echo "... Source/OTService/OTServicePlaylist.i"
	@echo "... Source/OTService/OTServicePlaylist.s"
	@echo "... Source/OTService/OTServiceStd.o"
	@echo "... Source/OTService/OTServiceStd.i"
	@echo "... Source/OTService/OTServiceStd.s"
	@echo "... Source/OTSession.o"
	@echo "... Source/OTSession.i"
	@echo "... Source/OTSession.s"
	@echo "... Source/OTSessionRefresh.o"
	@echo "... Source/OTSessionRefresh.i"
	@echo "... Source/OTSessionRefresh.s"
	@echo "... Source/OTString.o"
	@echo "... Source/OTString.i"
	@echo "... Source/OTString.s"
	@echo "... Source/OTUrlEncode.o"
	@echo "... Source/OTUrlEncode.i"
	@echo "... Source/OTUrlEncode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

