.TH openTIDAL_ModuleContainer 7 "04 Jan 2021" "libopenTIDAL 0.0.1" "libopenTIDAL Manual"
.SH NAME
openTIDAL_ModuleContainer \- Structure for module content
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "struct openTIDAL_ModuleContainer *modules;"
.SH STRUCTURE
.nf
int arraySize;
int arrayCapacity;
char **moduleType;
char **moduleTitle;
char **modulePreTitle;
int *arrayType;
int *offset;
int *total;

int mixedListSize;
int *mixedListTypes;
int *mixedListOffset;
int *mixedListTotal;
.fi
