.TH openTIDAL_SessionCreateFile 3 "04 Jan 2021" "libopenTIDAL 0.0.1" "libopenTIDAL Manual"
.SH NAME
openTIDAL_SessionCreateFile \- Create a persistent session configuration file
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "const int openTIDAL_SessionCreateFile (openTIDAL_SessionContainer *session);"
.SH DESCRIPTION
After a successful authentication with the oAuth device authorisation grant
(RFC 8628), call this function to create the persistent configuration file.
See \fIopenTIDAL_AuthCreateUserCode(3)\fP and \fIopenTIDAL_AuthCreateBearerToken(3)\fP
for login polling examples.

\fIopenTIDAL_SessionCreateFile(3)\fP allocates a stream of the newly created json
session configuration and writes it to the prior specified file location
\fIopenTIDAL_SessionInit(3)\fP.

Do not store any additional values inside the configuration file!
\fBlibopenTIDAL\fP(3) overwrites the configuration file after a successful session
oAuth access token renewal.

This function is only available if a file location was specified prior.
.SH RETURN VALUE
If successful \fIopenTIDAL_SessionCreateFile(3)\fP returns 0.

If an fopen error occurred (Could not write to file location) \fIopenTIDAL_SessionCreateFile(3)\fP returns -1.
