.TH openTIDAL_PlaylistContainer 7 "04 Jan 2021" "libopenTIDAL 0.0.1" "libopenTIDAL Manual"
.SH NAME
openTIDAL_PlaylistContainer \- Structure for playlist content
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "struct openTIDAL_PlaylistContainer *playlist;"
.SH STRUCTURE
.nf
.B Applied limit by the api.
int limit;
.B Applied offset by the api.
int offset;
int totalNumberOfItems;

int numberOfTracks;
int numberOfVideos;
char *uuid;
char *title;
char *description;
int duration;
char *lastUpdated;
char *created;
int publicPlaylist;
int popularity;
.B Playlist cover 128bit UUID. This UUID has to be concatenated into a URL.
char *image;
char *squareImage;
.B Editorial or user created.
char *type;
.fi
