.TH openTIDAL_MixContainer 7 "04 Jan 2021" "libopenTIDAL 0.0.1" "libopenTIDAL Manual"
.SH NAME
openTIDAL_MixContainer \- Structure for mix content
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "struct openTIDAL_MixContainer *mix;"
.SH STRUCTURE
.nf
.B Applied limit by the api.
int limit;
.B Applied offset by the api.
int offset;
int totalNumberOfItems;
    	
char *id;
char *title;
char *subTitle;
int smallImageWidth;
int smallImageHeight;
char *smallImageUrl;
int mediumImageWidth;
int mediumImageHeight;
char *mediumImageUrl;
int largeImageWidth;
int largeImageHeight;
char *largeImageUrl;
char *mixType;
.fi
