.TH OTJsonGetStringValue 3 "11 Jan 2021" "libopenTIDAL 1.0.0" "libopenTIDAL Manual"
.SH NAME
OTJsonGetStringValue \- Get string from object
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "char *OTJsonGetStringValue (const struct OTJsonContainer *const " item ");"
.SH DESCRIPTION
Get an ASCII string from an object that represents a json string.
Instead of calling \fIOTJsonGetObjectItem(3)\fP use \fIOTJsonGetObjectItemStringValue(3)\fP
to find the object.
DO NOT deallocate the ASCII string manually.
\fIOTDeallocContainer\fP handles \fIOTJsonContainer(7)\fP tree deallocation
by iterating over the tree and its values.
.SH RETURN VALUE
If the object is a valid string an ASCII string gets returned.
Otherwise, a NULL pointer gets returned.
.SH "SEE ALSO"
.BR OTJsonGetObjectItemStringValue "(3), " OTJsonGetNumberValue "(3), " OTJsonGetObjectItemNumberValue "(3), "
.BR OTJsonGetObjectItem "(3), " OTJsonHasObjectItem "(3), " OTJsonIsString "(3) "
