.TH OTJsonIsBool 3 "11 Jan 2021" "libopenTIDAL 1.0.0" "libopenTIDAL Manual"
.SH NAME
OTJsonIsBool \- Check for a boolean value
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "int OTJsonIsBool (const struct OTJsonContainer *const " item ");"
.SH DESCRIPTION
Check an object for a json boolean value.
.SH RETURN VALUE
Returns either 1 or 0 as an integer value.
.SH "SEE ALSO"
.BR OTJsonIsInvalid "(3), " OTJsonIsFalse "(3), " OTJsonIsTrue "(3), "
.BR OTJsonIsNull "(3), " OTJsonIsNumber "(3), " OTJsonIsString "(3) "
