.TH OTSessionCleanup 3 "11 Jan 2021" "libopenTIDAL 1.0.0" "libopenTIDAL Manual"
.SH NAME
OTSessionCleanup \- End a libopenTIDAL session handle
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "void OTSessionCleanup (struct OTSessionContainer *" session ");"
.SH DESCRIPTION
This function must be the last function to call for a \fBlibopenTIDAL\fP(3) session.
It deallocated the memory allocation performed by the \fIOTSessionInit(3)\fP
function. It is the opposite of the init function and must be called with
the same session as input that a \fIOTSessionInit(3)\fP call allocated.

Do not call this function if you intend to call more \fBlibopenTIDAL\fP(3) service
functions.

Any use of the session or the \fBlibopenTIDAL\fP(3) service functions without
reinitialising is illegal. \fIOTSessionCleanup\fP(3) deallocates all memory
associated with the session and kills the curl handle.
.SH RETURN VALUE
None
.SH EXAMPLE
.nf
struct OTSessionContainer *session = OTSessionInit ();
if (session)
    {
        OTSessionClientPair ({clientId}, {clientSecret}); 
        /* do smth with the session if OTSessionClientPair returns 0 */
    }
OTSessionCleanup (session);
.fi
.SH "SEE ALSO"
.BR OTSessionInit "(3), " OTSessionLogin "(3) "
