.TH OTServiceGetFavorites 3 "11 Jan 2021" "libopenTIDAL 1.0.0" "libopenTIDAL Manual"
.SH NAME
OTServiceGetFavorites \- Request user-based metadata
.SH SYNOPSIS
.B #include <openTIDAL/openTIDAL.h>

.BI "struct OTContentContainer *OTServiceGetFavorites (struct OTSessionContainer *" session ", const char *const " suffix ", const int " limit ", const int " offset ", const char *const " order ", const char *const " orderDirection ", void *threadHandle);"
.SH DESCRIPTION
The OTServiceGetFavorites service function requests TIDAL metadata.
The prefix and suffix parameter are used to specify the endpoint of the request.
This service call \fBmust\fP have a corresponding call to \fIOTDeallocContainer(3)\fP when the operation is complete.

.nf
.B Suffixes
"ids", "albums", "tracks", "videos", "artists", "playlists", "mixes"

.B Pagination
.fi
Use the limit and offset parameters to control metadata pagination.
Keep in mind that the TIDAL API will error out on certain limits.

.nf
.B Sorting
.fi
order: "DATE", "NAME", "ARTIST", "RELEASE_DATE", "MIX_TYPE"

orderDirection: "ASC", "DESC"

.nf
.B Thread Handle
.fi
You must never share the same handle in multiple threads. You can pass the handles around among threads, but you must never use a single handle from more than one thread at any given time.

Use the session main handle by parsing a NULL pointer.
.SH RETURN VALUE
If no memory allocation error occurred in allocating the \fIOTContentContainer(7)\fP, a
pointer to an \fIOTContentContainer(7)\fP will be returned.
Otherwise a NULL pointer will be returned.
.SH "SEE ALSO"
.BR OTServiceGetStandard "(3), " OTServiceGetPage "(3), "
.BR OTServiceSearch "(3), " OTServiceGetStream "(3), " OTServiceCreatePlaylist "(3) "
