.TH OTTypes 7 "11 Jan 2021" "libopenTIDAL 1.0.0" "libopenTIDAL Manual"
.SH NAME
OTTypes \- Container types
.SH DESCRIPTION
.SH "OTTypes"
.IP "SESSION_CONTAINER (0)"
libopenTIDAL session data structure.
.IP "CONTENT_CONTAINER (1)"
Standard libopenTIDAL content data structure. 
.IP "CONTENT_STREAM_CONTAINER"
Similar to the standard container with another nested OTJsonContainer. 
.SH "SEE ALSO"
.BR OTSessionContainer "(7), " OTContentContainer "(7), " OTContentStreamContainer "(7), "
.BR OTQuality "(7), " OTStatus "(7) "
